name: Smart Deploy or Destroy Azure Function App

on:
  push:
    branches:
      - featurebranch
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform: apply or destroy'
        required: true
        default: 'destroy'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:  
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Smart Plan
        id: plan
        run: |
          action="${{ github.event.inputs.action }}"
          if [ -z "$action" ]; then
            action="destroy"
          fi

          echo "Action: $action"

          if [ "$action" == "destroy" ]; then
            echo "Running destroy plan..."
            terraform plan -destroy -out=tfplan > plan_output.txt

            echo "Plan output:"
            cat plan_output.txt

            if grep -q "No changes. Infrastructure is up-to-date." plan_output.txt || grep -q "0 to destroy" plan_output.txt; then
              echo "Nothing to destroy — switching to apply instead."
              echo "FINAL_ACTION=apply" >> $GITHUB_ENV
            else
              echo "FINAL_ACTION=destroy" >> $GITHUB_ENV
            fi
          else
            terraform plan -out=tfplan
            echo "FINAL_ACTION=apply" >> $GITHUB_ENV
          fi

      - name: Terraform Apply or Destroy
        run: |
          echo "Final action is: $FINAL_ACTION"

          if [ "$FINAL_ACTION" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi

