    
    - name: Check and Import critical resources (main + AKS MC RG)
      id: import
      run: |
        RG_NAME="DevRG"
        AKS_NAME="kritagyaaks1"
        LOCATION="uksouth"
        MC_RG_NAME="MC_${RG_NAME}_${AKS_NAME}_${LOCATION}"

        echo "Checking if $RG_NAME exists in Azure..."
        EXISTS_MAIN=$(az group exists --name "$RG_NAME")

        echo "Checking if $MC_RG_NAME exists in Azure..."
        EXISTS_MC=$(az group exists --name "$MC_RG_NAME")

        echo "Checking Terraform state for main RG..."
        terraform state list | grep "azurerm_resource_group.example" || IN_STATE_MAIN="no"

        echo "Checking Terraform state for MC RG..."
        terraform state list | grep "azurerm_resource_group.mc_node_rg" || IN_STATE_MC="no"

        if [ "$EXISTS_MAIN" == "true" ] && [ "$IN_STATE_MAIN" == "no" ]; then
          echo "Main RG exists but not in state — importing..."
          terraform import azurerm_resource_group.example "/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/$RG_NAME"
        fi

        if [ "$EXISTS_MC" == "true" ] && [ "$IN_STATE_MC" == "no" ]; then
          echo "MC RG exists but not in state — importing..."
          terraform import azurerm_resource_group.mc_node_rg "/subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/$MC_RG_NAME"
        fi
