
name: Deploy or Destroy Azure Function App

on:
  push:
    branches:
      - featurebranch
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:  
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          action="${{ github.event.inputs.action }}"
          if [ -z "$action" ]; then
            action="apply"
          fi

          if [ "$action" == "destroy" ]; then
            terraform plan -destroy
          else
            terraform plan
          fi

      - name: Terraform Apply or Destroy
        run: |
          action="${{ github.event.inputs.action }}"
          if [ -z "$action" ]; then
            action="apply"
          fi

          if [ "$action" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
